### PR TITLE
Optimizations

### LINKED ISSUE #34: Performance improvements
There are a few opportunities to make Madoop faster.

- [x] Do not copy input.  Instead, read input files directly.  For larger files which need to be split, read an iterator over a segment of the input file.
- [x] Do not copy output.  Move final output instead of copying it.
- [ ] Do not store both map output and partitioned map output.  Instead, pipe map output directly to partition function.
- [ ] Do store both sorted and unsorted group output.  Instead, read partitioned mapper output into memory (one file).  Sort it.  Pipe sorted output to reducer input.
- [x] Measure run time with a large input (e.g., EECS 485 Project 5 Wikipedia input) and optimize input partition size.
- [x] Parallelism with a thread pool
- [x] Don't read intermediate files again to calculate statistics for DEBUG output.  This is a bad one and it even runs when DEBUG output is disabled. #41

### LINKED ISSUE #69: Don't open too many output files
When the input is _really_ big, sometimes Madoop will try to open _way_ too many output files and crash. 

In `mapreduce.py, prepare_input_files()`, we define a magic number `MAX_INPUT_SPLIT_SIZE` that ends up determining the number of output files we try to make, unbounded by anything.
Then we open all the output files at once in a loop with
```python
outfiles = [stack.enter_context(i.open('w')) for i in outpaths]
```

(This problem showed up once with the bigger dataset for P5. Depending on a student's OS and choice of intermediate output, the input size to a given MR job could be **massive**. The quick fix was to bump the value of `MAX_INPUT_SPLIT_SIZE` in their local environment, but we should fix it for real.)

Potential solutions:
1. Open output files one at a time instead
2. Use the `split` as a subprocess and avoid opening the files in Python

(CC + credit for solutions @MattyMay)

### PR DESCRIPTION
**Pull request by noah-weingarden**
Closes #34, closes #69. I deliberately chose not to make these two changes:

> Do not store both map output and partitioned map output. Instead, pipe map output directly to partition function.
Do not store both sorted and unsorted group output. Instead, read partitioned mapper output into memory (one file). Sort it. Pipe sorted output to reducer input.

I'm worried that, although these are legitimate optimizations, they would make Madoop significantly more similar to a project 4 solution. We would in fact be verbatim ripping off code from project 4, losing some of Madoop's distinctiveness in the process. Open to debate/suggestions on this though.

With regard to this:
> Measure run time with a large input (e.g., EECS 485 Project 5 Wikipedia input) and optimize input partition size.

I measured the runtime of project 5's job 1 and job 2 and found that, on my machine, it truthfully doesn't matter very much. Job 1, which is by far the slowest, is unaffected entirely since the actual input to the framework is minuscule (just a file with ~3,000 filenames,which I consider a severe flaw of the recent HTML dataset changes--see [this comment](https://github.com/eecs485staff/p5-search-engine/issues/686#issuecomment-1822599805)). Job 2 is minimally affected some of the time, but not all the time, and any chunk size higher than ~18 MB is pointless due to the size of the input files. I went with 10 MB as a compromise, as this and anything higher does seem to subtract a few seconds some of the time.

### CODE REVIEW

**Comment by noah-weingarden** [comment]
Note that because sorting intermediate files now happens in a subprocess, Coverage isn't figuring out that `sort_file()` actually runs. `pytest-cov` has [documentation](https://pytest-cov.readthedocs.io/en/latest/subprocess-support.html#if-you-use-multiprocessing-pool) about this, but their suggestion doesn't help. Since Coverage is still letting this pass CI, I lean toward ignoring this.

**Comment by awdeorio** [comment]
> I'm worried that, although these are legitimate optimizations, they would make Madoop significantly more similar to a project 4 solution. We would in fact be verbatim ripping off code from project 4, losing some of Madoop's distinctiveness in the process. Open to debate/suggestions on this though.

Good point.  I agree with you.

> I measured the runtime of project 5's job 1 and job 2  ...

This should be resolved soon once https://github.com/eecs485staff/p5-search-engine/pull/710 is finished editing and merged

**Review by awdeorio — COMMENTED** [review]
Overall LGTM once conflicts are resolved

**Comment by noah-weingarden** [comment]
Was there anything special about the 2 MB that #74 changed to or is 10 MB still good?

**Comment by awdeorio** [comment]
> Was there anything special about the 2 MB that https://github.com/eecs485staff/madoop/pull/74 changed to or is 10 MB still good?

Not sure.  @melodell ?

**Comment by melodell** [comment]
> > Was there anything special about the 2 MB that https://github.com/eecs485staff/madoop/pull/74 changed to or is 10 MB still good?
> 
> 
> 
> Not sure.  @melodell ?

Nope, just needed to bump it above 1 MB, since a handful of our documents were > 1 MB.

**Review by awdeorio — APPROVED** [review]
LGTM once the tests pass!  I merged in the latest develop and it looks like there's one failure that has to do with spaces in input paths.

EDIT: I think that the parallelization will be nice with https://github.com/eecs485staff/p5-search-engine/pull/710

**Comment by noah-weingarden** [comment]
> LGTM once the tests pass! I merged in the latest develop and it looks like there's one failure that has to do with spaces in input paths.

Fixed that--looks like the only issue left is that we got rate limited uploading codecov reports. Are we missing a token somehow?

**Comment by awdeorio** [comment]
> Looks like the only issue left is that we got rate limited uploading codecov reports. Are we missing a token perhaps?

Taking a look in #79

**Pull request merged**
