### PR TITLE
Hadoop Streaming Tutorial

### PR DESCRIPTION
**Pull request by jaredzh**
Move Hadoop Streaming Tutorial from P5 repo to Madoop repo.

Closes #38 

## TODO
- [x] Create a sibling PR in the P5 repo that updates the links in the p5 spec and removes the tutorial from the P5 spec
- [x] Create a sibling PR in the eecs485.org repo that updates the link in the comments

### CODE REVIEW

**Comment by jaredzh** [comment]
What would be the link for `example`? Do we need to upload it as a `tar.gz`? @awdeorio

**Comment by awdeorio** [comment]
> What would be the link for example? Do we need to upload it as a tar.gz? @awdeorio

Ohh, good point.  Yes.

**Comment by jaredzh** [comment]
No worries, it's all good! Yeah I wasn't sure whether you left them for you or for me so I just resolved them just in case it was for me lol. @awdeorio

**Comment by awdeorio** [comment]
I tried something to new to make it easy for someone to run the example program.  I added a `madoop --example` flag which copies the example files to the user's PWD.  WDYT?

```console
$ madoop --example
Created example, try:

madoop \
  -input example/input \
  -output output \
  -mapper example/map.py \
  -reducer example/reduce.py        
$ madoop \
  -input example/input \
  -output output \
  -mapper example/map.py \
  -reducer example/reduce.py  
INFO: Starting map stage
INFO: Finished map executions: 2
INFO: Starting group stage
INFO: Starting reduce stage
INFO: Finished reduce executions: 3
INFO: Output directory: output
```

**Comment by jaredzh** [comment]
> I tried something to new to make it easy for someone to run the example program. I added a `madoop --example` flag which copies the example files to the user's PWD. WDYT?
> 
> ```
> $ madoop --example
> Created example, try:
> 
> madoop \
>   -input example/input \
>   -output output \
>   -mapper example/map.py \
>   -reducer example/reduce.py        
> $ madoop \
>   -input example/input \
>   -output output \
>   -mapper example/map.py \
>   -reducer example/reduce.py  
> INFO: Starting map stage
> INFO: Finished map executions: 2
> INFO: Starting group stage
> INFO: Starting reduce stage
> INFO: Finished reduce executions: 3
> INFO: Output directory: output
> ```

I like this! This way they don't have to manually download the example files using wget.

**Comment by awdeorio** [comment]
OK!  I'll polish this up and let you know when it's ready for a read through.

**Review by awdeorio — COMMENTED** [review]
I made some changes and I think this is almost ready to go!  Would you mind taking a detailed look at my changes and then creating PRs in the P5 and eecs485.org repos?  @jaredzh

**Comment by jaredzh** [comment]
> I made some changes and I think this is almost ready to go! Would you mind taking a detailed look at my changes and then creating PRs in the P5 and eecs485.org repos? @jaredzh

Yeah sounds good.

**Comment by jaredzh** [comment]
LGTM after some nitpicks. Go ahead and approve and merge if it's good to you. @awdeorio

**Pull request merged**
